module.exports = {
  "ALIVE_IMG": "https://i.ibb.co/zZ13BVL/9674.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94769615736",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": true,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": false,
  "ANTI_CALL": false,
  "ANTI_DELETE": true,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "MR DAKSHINA",
  "NEWS_JID": "",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": false,
  "EMOJI": "🏷",
  "AI_MODE": false
};
